#!/usr/bin/env bash

echo "- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"
echo "- STARTING SOFTWARE INSTALLATION                              -"
echo "- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"

echo "powerline fonts"
sudo pacman -S --noconfirm powerline-fonts

echo "spotify daemon"
sudo pacman -S --noconfirm spotifyd 

echo "spotify tui client"
sudo pacman -S --noconfirm spotify-tui

echo "get antigen plugin manager"
curl -L git.io/antigen > antigen.zsh

echo "oh-my-zsh"
yaourt -S --noconfirm oh-my-zsh-git

echo "todoist"
yaourt -S --noconfirm todoist

echo "peco"
yaourt -S --noconfirm peco

echo "dnote"
curl -s https://www.getdnote.com/install | sh

echo "- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"
echo "- FINISHED SOFTWARE INSTALLATION                              -"
echo "- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"
